### ISSUE TITLE
Add back top level curly brackets

### ISSUE THREAD

**Issue by IvanGoncharov** [graphcool/gcl#1]
You removed top level curly brackets https://github.com/graphcool/gcl#config-file
IMHO it looks strange to me. If I see some config without any other objects like this:
```
image: "node:6.10"
ports: ["80"]
networks: ["frontend"]
```
I will assume it’s something like YAML and add sub objects like that:
```
ports: ["80"]
networks: ["frontend"]
deploy:
  replicas: 2
```
Also, there are a few technical issues.
Since you will be reusing vanilla GraphQL parser you will need to add curly brackets programmatically which means you need to correct column and/or line numbers inside error messages. 
It also would be significantly harder to reuse existing components like codemirror-graphql

**Comment by schickling** [comment]
Thanks a lot for bringing this up @IvanGoncharov! I definitely see the implementation/consistency benefits of using top level curly brackets, however think it's slightly more convenient to write when leaving them out.

I see your point regarding the YAML ambiguity but this argument also holds true for many other configuration languages such as [HCL](https://github.com/hashicorp/hcl).

I think ultimately we should opt for the most GraphQL idiomatic approach. @asiandrummer do you have opinion on this?

**Comment by asiandrummer** [comment]
@schickling thanks for including in the context - I'm honestly not sure if I can form any opinions at this point without the context of this project. I'd love to set up some time with you guys to chat more about it, potentially understand the motivation behind this.
